DROP TABLE  OAS.USER_ROLES;
DROP TABLE  OAS.ROLE_PERMISSIONS;
DROP TABLE  OAS.USERS;
DROP TABLE  OAS.ROLES;
DROP TABLE  OAS.PERMISSIONS;

CREATE TABLE OAS.USERS (
    ID INT NOT NULL,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    ENABLED  NUMERIC(1)  NOT NULL,
    PRIMARY KEY (ID)
); 

CREATE TABLE OAS.ROLES (
    ID INT NOT NULL,
    ROLENAME  VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID)    
); 

CREATE TABLE OAS.USER_ROLES (  
    USER_ID int NOT NULL CONSTRAINT USER_FK  REFERENCES OAS.USERS (ID) ON DELETE CASCADE ON UPDATE RESTRICT,  
    ROLE_ID int NOT NULL CONSTRAINT ROLE_FK  REFERENCES OAS.ROLES (ID) ON DELETE CASCADE ON UPDATE RESTRICT      
);

CREATE TABLE OAS.PERMISSIONS (
    ID INT NOT NULL ,
    PERMISSIONNAME VARCHAR(50) NOT NULL,
    PRIMARY KEY(ID)    
) ;

CREATE TABLE OAS.ROLE_PERMISSIONS (
    ROLE_ID   INT     NOT NULL,
    PERMISSION_ID INT  NOT NULL,
    FOREIGN KEY (ROLE_ID) REFERENCES OAS.ROLES (ID) ON DELETE CASCADE ON UPDATE RESTRICT,
    FOREIGN KEY (PERMISSION_ID) REFERENCES OAS.PERMISSIONS (ID) ON DELETE CASCADE ON UPDATE RESTRICT
) ;
